### ISSUE TITLE
8IOL AOI: When download PLC, VID is not properly updated

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#15]
Looks like it needs a time delay like we do for disconnect, maybe add it as part of the prescan. 

To replicate: connect a device, when online with PLC save project while uploading the values. Then connect a different device and download. It will initially show up as the "saved" device until something changes enough to trigger a re-check.

**Comment by jose-sanchez-tcan** [comment]
![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/7ab70b9a-98d6-4860-bb4d-b87c26e4f4a3)

I don't have another device to try, but I added a 500ms delay to start the whole READ / WRITE process, does this work? 

To be tested.
