### ISSUE TITLE
8IOL AOI: Make sure to write the Datamapping C data

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#18]

**Comment by jose-sanchez-tcan** [comment]
Force it to be direct for IN/OUT and port settings only for ports in use.

**Comment by jose-sanchez-tcan** [comment]
![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/d953dd11-d542-42f2-b19e-4a4e418333e0)

Moved 0 to the input/output data mapping.
