### ISSUE TITLE
Generic AOIs for Devices not setup yet

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#19]

**Comment by nickcluteturck** [comment]
Include input parameters to switch data mapping (swap 16, 32, all)

**Comment by nickcluteturck** [comment]
1 version in words, 1 version in bytes?

**Comment by jose-sanchez-tcan** [comment]
First draft with INTs created, inputs for swap added but not working for now.

**Comment by jose-sanchez-tcan** [comment]
Swapping not added since it requires size of process data. Will release w/o this function. V1.0
