### ISSUE TITLE
Read Index before Writing in 8IOL AOI

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#2]

**Comment by jose-sanchez-tcan** [comment]
Can you refresh my memory on this one? Is this related to index 68?

**Comment by nickcluteturck** [comment]
This one we haven't discussed yet. Basically because parameters are stored in EEPROM memory they only can be written 100k times, so it's good practice to Read the value first and only write it if it has changed. I was thinking it would make sense to build this into the 8IOL AOI instead of writing it into every device AOI.
________________________________

**Comment by jose-sanchez-tcan** [comment]
We will be reading any index we're writing in the device AOI anyways. So no need to burden the TBEN 8IOL with a mechanism for preventing reads since this will be happening at device AOIs already.
