### ISSUE TITLE
8IOL AOI: Restructure Common Data Process Data into Arrays of data by port 

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#23]
Process Data as INT[] becomes Generic_16_Words[7]

**Comment by jose-sanchez-tcan** [comment]
Used INT[16] for each port. 
![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/8de353fc-0319-4453-bf6b-ac417794a02a)

![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/c63238cb-73d2-402f-855c-7b65ac72d149)

**Comment by jose-sanchez-tcan** [comment]
Changed to Generic 16 words per port:

![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/6e1f9ba5-e19a-438b-8b12-c39e7a48d896)

![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/10f7cb41-470d-4261-b82c-87d705d8316d)

**Comment by jose-sanchez-tcan** [comment]
![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/c8a9decd-0b69-4cc1-ac74-df8775b335de)

![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/1e4ed544-fd2d-4b0e-a468-f4556cf8026a)

**Comment by jose-sanchez-tcan** [comment]
Now done using proper CPS
