### ISSUE TITLE
8IOL AOI: Remove the need for CPS by changing the Input type

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#25]
Anthony reminded me that when we're grabbing an entire data structure we don't need to use CPS commands to get data in/out of the block. Please update the 8IOL AOI to utilize this structure:
![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/134663076/59f34a04-d42f-4d8b-995e-4ada9d7eadb2)

**Comment by jose-sanchez-tcan** [comment]
Done, just missing the GSV side of things:

![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/41ff4c57-f2d4-4de8-b6b2-e6fbfcbe80f6)
