### ISSUE TITLE
Improper Rev Revision in Universal_Device_Info.L5X?

### ISSUE THREAD

**Issue by Kyle-Haaallll** [nickcluteturck/IOLinkAOIs#32]
If Universal_Device_Info.L5X was changed the revision on the AOI needs to be set to 1.x or 2 so other devs know which is newest.  I can't tell if the Universal_Device_Info.L5X I had is any difference then the one just downloaded that was updated 2 weeks ago w/o inspecting the code rung by rung.  No time for that.
![IOL_Test_Bug_10-12-2023](https://github.com/nickcluteturck/IOLinkAOIs/assets/147733078/6ea577a8-82a6-43e6-9642-11120ee53bd3)

**Comment by nickcluteturck** [comment]
Original issue was due to 0.2 not being complete, hence why it wasn't in the catalog file. That being said, the current version pushed today (V1.1) has corrected versioning in AOI.
