### ISSUE TITLE
8IOL AOI: Dowloading project with uploaded tags, doesn't trigger to reread VID/DID

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#44]
Process: connect device to a port, save and upload tags, go offline, make a change to an aoi, unplug device and plug another one, download project. Doesn't think there was a change in port info so doesn't reread and thus thinks its the old uploaded device.

Created a panic attack as I thought my TBIL-M1-16DXP was reporting as TBIL-S4-8DXP....lol.

**Comment by jose-sanchez-tcan** [comment]
look at the univeesal device info AOI (built in bit in the processor), it uses processor bit to clear arrays so this AOI could use something similar

**Comment by jose-sanchez-tcan** [comment]
Connected a Radar sensor on port 6, saved and uploaded tags, then went offline and changed port on universal device info and plug a TBIL device on port 1 instead. Finally downloaded project and back to run. TBEN AOI shows device on port 1 and all data is blank for Universal device info AOI as expected with the recent changes.
