### ISSUE TITLE
8IOL AOI: Wonky Ticket Handling on PLC Download

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#46]
When working on the PS+ AOI, I was testing to make sure the verification we were in the correct Process Data Profile and making sure we had the analog output function disabled was working, so I would write the incorrect values using Webserver and downloaded the project. One value returned a 0 when the index was clearly a 4 and the other never actually gave us a Done or Error so hung the state machine for that read. Retriggering the commands worked great, and if I delayed sending commands for 5s it also worked great. I suspect we need to have a startup delay in the 8IOL AOI before we start to process tickets.

**Comment by nickcluteturck** [comment]
Ran into this again for reasons (Downloading previous tag values so not resetting a latched bit on startup and having a race condition where the evaluation of TON.ACC was before the resetting of the timer) and found that as little as a 500ms (250ms was too short) and interestingly it was only 1 of the 2 Indices I was testing that was "slow" (Display Rotation Index 91 of PS+), Units Index 84 was happy going fast, I found the issue when testing Index 80 - Process Data Profile.

**Comment by jose-sanchez-tcan** [comment]
Should be fixed with recent changes as well.
