### ISSUE TITLE
8IOL AOI: Data Storage Mode Activated unexpectedly?

### ISSUE THREAD

**Issue by nickcluteturck** [nickcluteturck/IOLinkAOIs#48]
Somehow my C data was set to activate Data Storage Mode (all 0s in those bytes). Do we want to make the AOI take control of these bytes?

**Comment by jose-sanchez-tcan** [comment]
Inclined to set them all to deactivated

**Comment by jose-sanchez-tcan** [comment]
![image](https://github.com/nickcluteturck/IOLinkAOIs/assets/137210485/4c117bcf-2afa-4b9a-be62-06c3c454e3da)
set all ports to DS deaactivated.
