### ISSUE TITLE
If port is set to zero  it creates a major fault on the PLC 

### ISSUE THREAD

**Issue by jose-sanchez-tcan** [nickcluteturck/IOLinkAOIs#51]

**Comment by jose-sanchez-tcan** [comment]
I was testing using a "port" variable instead of a fix value to accelerate testing time., since it's initialized at 0 it generates a major fault on the PLC. It's not unfeasible to think a customer would enter a 0 there, specially when confusing C0 with port 1.  

For now I added an LES on the Generic Process Data AOI to set the Port value (Port_Less_One) to 0 if it gets a value less than 0.

I tested setting port to 0 on the universal device info and also got a major fault.

**Comment by jose-sanchez-tcan** [comment]
Generic process AOI was corrected.

**Comment by nickcluteturck** [comment]
All other device AOIs and generic have been corrected.
